export const REQUEST_ALL_QUESTIONS = "REQUEST_ALL_QUESTIONS";
export const REQUEST_ALL_USERS = "REQUEST_ALL_USERS";
export const REQUEST_ALL_TOPICS = "REQUEST_ALL_TOPICS";
export const RECEIVE_ALL_QUESTIONS = "RECEIVE_ALL_QUESTIONS";
export const RECEIVE_ALL_USERS = "RECEIVE_ALL_USERS";
export const RECEIVE_ALL_TOPICS = "RECEIVE_ALL_TOPICS";
